export const DESIGN_STATUS = {
  DRAFT: 'DRAFT',
  CONTENT_GENERATING: 'CONTENT_GENERATING',
  REVIEW: 'REVIEW',
  APPROVED: 'APPROVED',
  PUBLISHING: 'PUBLISHING',
  LIVE: 'LIVE',
  ARCHIVED: 'ARCHIVED',
} as const

export const PRODUCT_TYPE = {
  INDUCTION: 'INDUCTION',
  CIRCLE: 'CIRCLE',
  SPLASH: 'SPLASH',
} as const

export const WORKFLOW_STEP = {
  DESIGN_UPLOAD: 'DESIGN_UPLOAD',
  CONTENT_GENERATION: 'CONTENT_GENERATION',
  AI_REVIEW: 'AI_REVIEW',
  TRANSLATION: 'TRANSLATION',
  MOCKUP_GENERATION: 'MOCKUP_GENERATION',
  PRINTFILE_GENERATION: 'PRINTFILE_GENERATION',
  NOTION_SYNC: 'NOTION_SYNC',
  EAN_GENERATION: 'EAN_GENERATION',
  SHOPIFY_PUBLISH: 'SHOPIFY_PUBLISH',
  FINAL_REVIEW: 'FINAL_REVIEW',
} as const

export const STEP_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
} as const

export const TRANSLATION_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const

export const SUPPORTED_LANGUAGES = ['nl', 'de', 'en', 'fr'] as const
export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number]

export const PRODUCT_SKU_PREFIX = {
  INDUCTION: 'IB',
  CIRCLE: 'MC',
  SPLASH: 'SP',
} as const
